using Cashback.Domain.Common;
using Cashback.Domain.Enums;

namespace Cashback.Domain.Entities;

/// <summary>
/// Affiliate conversion order received from a provider.
/// </summary>
public class Order : AuditableEntity
{
    /// <summary>
    /// User who earned cashback from the order.
    /// </summary>
    public Guid UserId { get; private set; }

    /// <summary>
    /// Affiliate link associated with the conversion.
    /// </summary>
    public Guid? AffiliateLinkId { get; private set; }

    /// <summary>
    /// Unique order identifier from the affiliate network.
    /// </summary>
    public string NetworkOrderId { get; private set; } = null!;

    /// <summary>
    /// Merchant where the order was placed.
    /// </summary>
    public MerchantType? Merchant { get; private set; }

    /// <summary>
    /// Total order value reported by the provider.
    /// </summary>
    public decimal? OrderAmount { get; private set; }

    /// <summary>
    /// Commission amount received from the provider.
    /// </summary>
    public decimal CommissionAmount { get; private set; }

    /// <summary>
    /// Cashback amount credited to the user.
    /// </summary>
    public decimal CashbackAmount { get; private set; }

    /// <summary>
    /// Platform profit retained from the commission.
    /// </summary>
    public decimal PlatformProfit { get; private set; }

    /// <summary>
    /// Current lifecycle status of the order.
    /// </summary>
    public OrderStatus Status { get; private set; }

    /// <summary>
    /// UTC timestamp when the order occurred at the merchant.
    /// </summary>
    public DateTime? OrderDate { get; private set; }

    /// <summary>
    /// User associated with the order.
    /// </summary>
    public User User { get; private set; } = null!;

    /// <summary>
    /// Affiliate link associated with the order.
    /// </summary>
    public AffiliateLink? AffiliateLink { get; private set; }

    /// <summary>
    /// Commission transactions generated by the order.
    /// </summary>
    public ICollection<CommissionTransaction> CommissionTransactions { get; private set; } = [];
}
