using Cashback.Domain.Common;
using Cashback.Domain.Enums;

namespace Cashback.Domain.Entities;

/// <summary>
/// Platform user account with authentication and balance information.
/// </summary>
public class User : AuditableEntity
{
    /// <summary>
    /// User email address.
    /// </summary>
    public string Email { get; private set; } = null!;

    /// <summary>
    /// Hashed password for local authentication.
    /// </summary>
    public string? PasswordHash { get; private set; }

    /// <summary>
    /// User display name.
    /// </summary>
    public string FullName { get; private set; } = null!;

    /// <summary>
    /// URL of the user avatar image.
    /// </summary>
    public string? AvatarUrl { get; private set; }

    /// <summary>
    /// Authentication provider used by the user.
    /// </summary>
    public AuthProvider Provider { get; private set; }

    /// <summary>
    /// External provider user identifier.
    /// </summary>
    public string? ProviderUserId { get; private set; }

    /// <summary>
    /// User role defining platform permissions.
    /// </summary>
    public UserRole Role { get; private set; }

    /// <summary>
    /// Indicates whether the user account is active.
    /// </summary>
    public bool IsActive { get; private set; }

    /// <summary>
    /// Indicates whether the user email has been verified.
    /// </summary>
    public bool EmailVerified { get; private set; }

    /// <summary>
    /// Balance available for withdrawal.
    /// </summary>
    public decimal AvailableBalance { get; private set; }

    /// <summary>
    /// Cashback amount awaiting approval.
    /// </summary>
    public decimal PendingBalance { get; private set; }

    /// <summary>
    /// Total approved cashback earned by the user.
    /// </summary>
    public decimal LifetimeCashback { get; private set; }

    /// <summary>
    /// UTC timestamp of the most recent login.
    /// </summary>
    public DateTime? LastLoginAt { get; private set; }

    /// <summary>
    /// Affiliate links generated by the user.
    /// </summary>
    public ICollection<AffiliateLink> AffiliateLinks { get; private set; } = [];

    /// <summary>
    /// Orders associated with the user.
    /// </summary>
    public ICollection<Order> Orders { get; private set; } = [];

    /// <summary>
    /// Commission transactions recorded for the user.
    /// </summary>
    public ICollection<CommissionTransaction> CommissionTransactions { get; private set; } = [];

    /// <summary>
    /// Withdrawal requests submitted by the user.
    /// </summary>
    public ICollection<WithdrawRequest> WithdrawRequests { get; private set; } = [];

    /// <summary>
    /// Notifications sent to the user.
    /// </summary>
    public ICollection<Notification> Notifications { get; private set; } = [];
}
