using Cashback.Domain.Common;
using Cashback.Domain.Enums;

namespace Cashback.Domain.Entities;

/// <summary>
/// Platform user account with authentication and balance information.
/// </summary>
public class User : AuditableEntity
{
    /// <summary>
    /// User email address.
    /// </summary>
    public string Email { get; private set; } = null!;

    /// <summary>
    /// Hashed password for local authentication.
    /// </summary>
    public string? PasswordHash { get; private set; }

    /// <summary>
    /// User display name.
    /// </summary>
    public string FullName { get; private set; } = null!;

    /// <summary>
    /// URL of the user avatar image.
    /// </summary>
    public string? AvatarUrl { get; private set; }

    /// <summary>
    /// Authentication provider used by the user.
    /// </summary>
    public AuthProvider Provider { get; private set; }

    /// <summary>
    /// External provider user identifier.
    /// </summary>
    public string? ProviderUserId { get; private set; }

    /// <summary>
    /// User role defining platform permissions.
    /// </summary>
    public UserRole Role { get; private set; }

    /// <summary>
    /// Current lifecycle status of the user account.
    /// </summary>
    public UserStatus Status { get; private set; }

    /// <summary>
    /// Indicates whether the user email has been verified.
    /// </summary>
    public bool EmailVerified { get; private set; }

    /// <summary>
    /// Balance available for withdrawal.
    /// </summary>
    public decimal AvailableBalance { get; private set; }

    /// <summary>
    /// Cashback amount awaiting approval.
    /// </summary>
    public decimal PendingBalance { get; private set; }

    /// <summary>
    /// Total approved cashback earned by the user.
    /// </summary>
    public decimal LifetimeCashback { get; private set; }

    /// <summary>
    /// UTC timestamp of the most recent login.
    /// </summary>
    public DateTime? LastLoginAt { get; private set; }

    /// <summary>
    /// Affiliate links generated by the user.
    /// </summary>
    public ICollection<AffiliateLink> AffiliateLinks { get; private set; } = [];

    /// <summary>
    /// Orders associated with the user.
    /// </summary>
    public ICollection<Order> Orders { get; private set; } = [];

    /// <summary>
    /// Financial transactions recorded for the user.
    /// </summary>
    public ICollection<Transaction> Transactions { get; private set; } = [];

    /// <summary>
    /// Withdrawal requests submitted by the user.
    /// </summary>
    public ICollection<Withdrawal> Withdrawals { get; private set; } = [];

    /// <summary>
    /// Notifications sent to the user.
    /// </summary>
    public ICollection<Notification> Notifications { get; private set; } = [];

    /// <summary>
    /// Refresh tokens issued to the user.
    /// </summary>
    public ICollection<UserRefreshToken> RefreshTokens { get; private set; } = [];

    /// <summary>
    /// Required by Entity Framework.
    /// </summary>
    private User()
    {
    }

    /// <summary>
    /// Creates a new user account.
    /// </summary>
    public static User Create(
        string email,
        string fullName,
        AuthProvider provider,
        string? providerUserId = null,
        string? avatarUrl = null,
        UserRole role = UserRole.User)
    {
        var now = DateTime.UtcNow;

        return new User
        {
            Id = Guid.NewGuid(),
            Email = email,
            FullName = fullName,
            AvatarUrl = avatarUrl,
            Provider = provider,
            ProviderUserId = providerUserId,
            Role = role,
            Status = UserStatus.Active,
            EmailVerified = provider != AuthProvider.Local,
            AvailableBalance = 0,
            PendingBalance = 0,
            LifetimeCashback = 0,
            CreatedAt = now,
            UpdatedAt = now
        };
    }

    /// <summary>
    /// Updates the user profile display information.
    /// </summary>
    public void UpdateProfile(string fullName, string? avatarUrl)
    {
        FullName = fullName;
        AvatarUrl = avatarUrl;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Synchronizes profile data from Google and records login.
    /// </summary>
    public void SyncGoogleProfile(string fullName, string? avatarUrl)
    {
        FullName = fullName;
        AvatarUrl = avatarUrl;
        RecordLogin();
    }

    /// <summary>
    /// Indicates whether the user can authenticate.
    /// </summary>
    public bool CanLogin()
    {
        return Status == UserStatus.Active;
    }

    /// <summary>
    /// Records a successful login timestamp.
    /// </summary>
    public void RecordLogin()
    {
        LastLoginAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Suspends the user account.
    /// </summary>
    public void Suspend()
    {
        Status = UserStatus.Suspended;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Reactivates a suspended user account.
    /// </summary>
    public void Activate()
    {
        Status = UserStatus.Active;
        UpdatedAt = DateTime.UtcNow;
    }
}
